# ./config.yaml

# Logging configuration
logging:
  file_path: "./logs/scraper.log"
  level: "INFO"
  max_size: 10485760  # 10MB in bytes
  backup_count: 5     # Number of backup files to keep

# Rate limiting settings
rate_limits:
  requests_per_minute: 240  # API limit
  delay_between_accounts: 2.0  # Seconds
  delay_between_posts: 0.5    # Seconds

# Airtable configuration
airtable:
  api_key: "${AIRTABLE_API_KEY}"
  base_id: "${ACCOUNT_ARMY_BASE_ID}"
  active_accounts_table: "${ACTIVE_ACCOUNTS_TABLE_ID}"

# ✅ Instagram API configuration — this was missing
instagram:
  api_key: "${RAPIDAPI_KEY}"
  host: "social-api4.p.rapidapi.com"